spring:
  application:
    name: flight-search-service
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080